# basic info
PROGRAM_NAME = "The Chesser"

# character keywords
COMMENT_CHARACTER = "/"
IMPORT_CHARACTER = "@"
IMPORT_CHARACTER_AGAINST = "!"
OPENING_OBJECT_CHARACTER = "{"
CLOSING_OBJECT_CHARACTER = "}"

# opening files metadata
OPENINGS_PATH = "./openings"
OPENINGS_EXTENSION = "cl"
OPENINGS_COUNTER_PREFIX = "Vs"
PRIMARY_WHITE = "ForWhite"
PRIMARY_BLACK = "ForBlack"

# function usage
MOVE_SEPARATOR = " "
CASE_SENSITIVE = False

# CLI
MOVE_HISTORY_BORDER = "|"

